### ISSUE TITLE
Individual queries are less efficient/usable

### ISSUE THREAD

**Issue by brookr** [6529-Collections/nftdelegation#16]
If I'm reading this correctly, the collection will need to make an individual query to the delegations contract for each and every address holding a NFT in the collection. 

Eg: Yuga Labs wants to airdrop something to the delegated wallet of every Mutant Ape holder. That's 12,476 times they'd need to invoke the delegation contract, just to see if a delegated wallet has been set up. 

There will be wasted gas in the overhead of making each of these calls individually. 

Instead, the delegations contract should have a method like `retrieveActiveToDelegationsForCollectionByUsecase`, where the `collectionAddress` and the `useCase` are the only things provided in a single query, and all delegated mappings are returned. 

This recognizes the reality that not all holders within the collection will use delegation at all, so the retrieval of delegations could be much more efficient. 

The comment in the code almost makes it seem like this function is intending this:

```solidity
    /**
     * @notice Returns an array of all active delegations on a certain date for a specific use case on a specific NFT collection
     *
     */
     function retrieveActiveToDelegations(address _profileAddress, address _collectionAddress, uint256 _date, uint256 _useCase) external view returns (address[] memory ) {
```

But here the `_profileAddress` is needed to create the hash to look up the data... which is stored with the delegator's address. So this function needs to be called with each collection holder's address. 

I'd imagine an implementation that returns the full set of delegations for a collection would need to track some extra global vars, like `registeredDelegationByCollection`, which would be maintained with every new delegation created, and pruned with every delegation revoked.

**Comment by rookmate** [comment]
I like this idea a lot. One of my main pet peeves with this implementation of delegation is that you cannot easily read the hashmaps to figure out the delegated address per wallet/collection/tokenId as the output is stored in a hash of multiple variables.

That is my main concern on this implementation. You need to spend a lot of gas to retrieve basic information as you described

**Comment by brookr** [comment]
Good news! It looks like the 4.33 release is addressing this issue, with functions like `retrieveTokenIDsToDelegationAddressesPerUsecaseForCollection`. Thanks, @skyn3t2030, for taking this into consideration, this is a huge usability improvement. 

(I'll leave the issue open for the maintainer to confirm.)

**Comment by skyn3t2030** [comment]
retrieveTokenIDsToDelegationAddressesPerUsecaseForCollection in the previous release is not yet part of the newer release 5.16. In any case it will function similar to retrieveTokensIDsandExpiredDatesFromDelegation that needs a profile address to execute. Retrieving all delegation addresses given only a collection is not part of the current implementation as we think it won't be useful. A team that wants to find this kind of information can extract it from the registerDelegation event in the contract's events logs.
