### ISSUE TITLE
Why are we registering use cases on chain?

### ISSUE THREAD

**Issue by rookmate** [6529-Collections/nftdelegation#2]
It makes it more gas expensive for a user to re-purpose a wallet address as they eventually need to remove it and then re-assign it as per the use cases. 

Whereas if it is on the user to manage we would not need the use cases right?

What is the main goal of storing that piece of information on the hash?

**Comment by Psifour** [comment]
The use cases provide a way for the delegator to store a small amount of additional data (1 nibble:4 bits) that can be used by associated contracts/services to determine the intent of the delegation. 

They can be thought of as flags that a third-party service can use (or ignore) as needed unless the community chooses to comply with the proposed mapping presented in the README (which I have some concerns with as it doesn't allow multiple selections at once like a proper bit mapping would).

As these are likely to be stored as uint96 (for gas efficiency), it would be nice to see the available range expanded a fair bit.

**Comment by rookmate** [comment]
If you're not going to go for bit masking you can even go for a uint8 as 256 use cases seem to be plenty.

Although I agree with you. bit masking is the way to go if you want to give multi purpose utility to a wallet

**Comment by Psifour** [comment]
I see #4 and #7 have already refactored the struct for better gas efficiency by switching to a uint96 (which packs into uint256 with an address). 96 unique addressable flags is definitely not 'necessary', but would enable more complex permissions while allowing us to set aside a fairly large set of them (apx. 80) as "user-defined".

**Comment by rookmate** [comment]
PR #1 already touches on this topic as well as other minor topics. Still I would like to see here a more feedback if people agree on the usefulness of the information

**Comment by skyn3t2030** [comment]
In newer release useCases are only registered now on-chain just to keep a track history. They were removed from mappings and structures.
