### ISSUE TITLE
Documentation proofreading

### ISSUE THREAD

**Issue by brookr** [6529-Collections/nftdelegation#22]
Hi, I'd like to contribute some documentation review. As per the contributing guide, i'll make an issue here to discuss. 

Here's what I have in mind:

1. Rename the contributing guide to CONTRIBUTING.md, which is pretty standard across OSS. See #20. 
2. Implement some markdown linting for the documentation pages, for improved authoring. See #21. 
3. Proofread docs for clarity, readability, accuracy, etc. In process... 

Please let me know your thoughts @skyn3t2030. And thanks again for the updated guidance on how to contribute! Looking forward to being a part of this project, in any way I can.

**Comment by skyn3t2030** [comment]
Thanks for your contributions, both PRs were approved.

**Comment by brookr** [comment]
Thanks, I'll spend some time during further reviews over the next few days. Much appreciated!

**Comment by brookr** [comment]
This is resolved enough to close out. Thanks for the merges!
