### ISSUE TITLE
Consider using Semantic Versioning

### ISSUE THREAD

**Issue by brookr** [6529-Collections/nftdelegation#23]
Can we please align the version numbers and releases with [SemVer](https://semver.org/)?

Using the `major.minor.patch` versioning will communicate clearly to anyone using the code what kind of changes are happening with each release. 

Since the code is not yet "in produciton" on mainnet, the current major version should be `0`. Breaking changes would then increment the major version, while changes that don't modify the interface would increment the minor version, and hot-fixes would increment the patch level.

**Comment by rookmate** [comment]
Completely agree
