### ISSUE TITLE
An approach to automated tests? 

### ISSUE THREAD

**Issue by brookr** [6529-Collections/nftdelegation#24]
Would be great to see some automated tests covering the core functionality of the contract. 

Is there a plan for tests? There is a PR that proposes some tests, but it would be great to know if this is the preferred tooling. Once we settle on how tests can/should be added, we can go to town on getting different edge cases tested.

**Comment by rookmate** [comment]
I do like foundry toolset for tests. The test section PR #3 would definitely be a good addition to this repo

**Comment by rookmate** [comment]
I see that PR #31 is suggesting Hardhat as the go to for automated testing. Personally, I think foundry is a much better option to go with
