### ISSUE TITLE
Code efficiency on loop condition

### ISSUE THREAD

**Issue by rookmate** [6529-Collections/nftdelegation#29]
There are minor improvements to the code that can be done that save a lot of gas in the long run since the code to be used by everyone and frequently.

The example in question is instead of `counter <= array.length - 1` to be `counter < array.length` we save on one subtraction before the comparison on each loop.

I will submit the PR shortly.

**Comment by rookmate** [comment]
Thoughts? @brookr PR #30

**Comment by brookr** [comment]
I think it's also more readable.

**Comment by rookmate** [comment]
Improved it further since `++i` is cheaper than `i++`.
