### ISSUE TITLE
Manual testing results: is this working as expected? 

### ISSUE THREAD

**Issue by brookr** [6529-Collections/nftdelegation#32]
I've worked through some very basic manual testing on Goerli. I'll run through my process here, and what I'm seeing... I may not be understanding how this is meant to work, but it's not working as I expected. Questions and concerns listed below.

All interactions with the contract described here were on Goerli, submitted through Etherscan here: https://goerli.etherscan.io/address/0x6a89aff3b4ea4cf323c32740289c8a1d703abec8

## Setup: Write contract

I started by connecting a wallet (0xd25...). I used Write Contract to call `registerDelegationAddress` with:
- _collectionAddress (address): 0x8888888888888888888888888888888888888888
- _delegationAddress (address): 0x0E5c3E22b7239CEf46f56741ff66369f3CfECb77
- _expiryDate (uint256): 1678838414
- _useCase (uint8): 1
- _allTokens (bool): true
- _tokenid (uint256): 0
 
This should create a delegation for **all** contracts, for **all** use cases, until tomorrow. 

*question 1:* is `_expiryDate` a unix epoch timestamp? I'm presuming so... 

## Test: Read contract

Now i'd expect to be able to retrieve that delegation info for any given contract or use case... *question 2:* that is how this should work, right? 

under Read Contract, I called `retrieveDelegationAddresses` with:
- _delegatorAddress (address): 0xD25A430B1Fe01439D4C5D361DAE57c17D4F4EE45
- _collectionAddress (address): 0x8888888888888888888888888888888888888888
- _useCase (uint8): 1

And... I get back the 0x0e5 addy, great! That works! 

## Fails with other parameters

However... if I change the collection addy OR the use case number, I get back **nothing**. 

I had presumed that checking for a delegation with any contract address (like 0x33FD426905F149f8376e227d0C9D3340AaD17aF1 or 0xd12E3fB8f9312A71ad3BBe3a5873bf31DC29196D, a manifold Goerli contract), would still return the delegation. But anything but 0x888... gives me back nothing. I can only get the right response if I request what is delegated for collection 0x888... 

I had also presumed that setting the delegation for any use case would return the delegated address for ANY individually requested use case. As of now, requesting the delegation for use case 2 (minting) give a blank response. I can only get a response if I request what is delegated for use case 1. 

So, _question 3:_ Am i doing it wrong? Is it not working, or am I not understanding how it's supposed to work? 

I'm really hoping the "all" settings would not require checkers to have to check those values as well...

**Comment by brookr** [comment]
Answers from discord: 

- Yes, this is working as expected
- Yes, `_expiryDate` is a unix epoch integer
- Yes, the `retrieveDelegationAddresses` function should return the mapped addy...
- Yes, I was understanding it wrong. As it's currently written, additional calls need to be made to check the "all contracts" case, and the "all use-cases" settings. So, up to 4 calls need to be made during minting. 

Dear Team, please consider a simplified and more efficient approach, where checking ANY contract ID would also check the ALL contract ID in the same call... and checking ANY use-case, would also check the ALL use-case value in the same call. 

i believe this streamlined dev experience will aid adoption.

**Comment by a2rocket** [comment]
More on https://github.com/6529-Collections/nftdelegation/blob/main/Documentation/Sample_Test_Cases.md
