### ISSUE TITLE
Simplify boolean return pattern? 

### ISSUE THREAD

**Issue by brookr** [6529-Collections/nftdelegation#35]
Code like:

```
        if (globalDelegationHashes[hash].length > 0) {
            return true;
        } else {
            return false;
        }
```

could be simplified to:

```
        return globalDelegationHashes[hash].length > 0
```

this pattern appears a few times in the code, so this would reduce the LOC meaningfully.

**Comment by rookmate** [comment]
It will also reduce cost to deploy  the initial contract and overall simplify the contract

**Comment by a2rocket** [comment]
merged with prxt PR.
