### ISSUE TITLE
Loop conditions rely on stored values

### ISSUE THREAD

**Issue by brookr** [6529-Collections/nftdelegation#37]
Solidity docs say:
>Gas Limit and Loops:

>Loops that do not have a fixed number of iterations, for example, loops that depend on storage values, have to be used carefully: Due to the block gas limit, transactions can only consume a certain amount of gas. Either explicitly or just due to normal operation, the number of iterations in a loop can grow beyond the block gas limit which can cause the complete contract to be stalled at a certain point. This may not apply to view functions that are only executed to read data from the blockchain. Still, such functions may be called by other contracts as part of on-chain operations and stall those. Please be explicit about such cases in the documentation of your contracts.

— https://docs.soliditylang.org/en/latest/security-considerations.html#gas-limit-and-loops 

Yet, this is exactly what the delegation contract is doing. There are many times in the code, like in the `retrieveActiveDelegations` function, where loops run over `allGlobalHashes.length` multiple times in the same function. 

What happens when this contract gets popular, and there are a LOT of delegations stored in the global hashes? These functions that loop over all items will get to be very costly in gas, and could even exceed the block gas limit. 

View functions may be different, but those can still stall other contracts that call them, as per the docs quoted above. 

Is this a significant concern? Why or why not?

**Comment by a2rocket** [comment]
Optimised loops by merging rookmate PR
