### ISSUE TITLE
Use case numbering consistency

### ISSUE THREAD

**Issue by brookr** [6529-Collections/nftdelegation#45]
Two special use-cases are excluded from "ALL" delegation assignment: consolidation and subdelegation. 

Consolidation is 99, which clearly distinct from all other uses cases. 

Subdelegation is 16, which means if any other use cases are used in later versions of this contract, they will have a higher number (17, 18, 19...). At that point, we can no longer say "ALL" refers to 15 and below, without complicated data migrations. 

I suggest changing subdelegation to be usecase id 98.

**Comment by a2rocket** [comment]
the subdelegation usecase changed to 98, please view version 5.20.13
